#!/usr/bin/env bash
# Regenerates THIRD_PARTY.md and licenses/ from go.mod (all transitive Go
# modules) plus the bundled data notes. licenses/ is gitignored; CI runs
# this at release time so every archive ships current notices.
set -euo pipefail
cd "$(dirname "$0")/.."

md="THIRD_PARTY.md"
licdir="licenses"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

go mod download
go list -m -f '{{if not .Main}}{{.Path}} {{.Version}} {{.Dir}}{{"\n"}}{{end}}' all > "$tmp"

rm -rf "$licdir"
mkdir -p "$licdir"

{
  echo "# Third-party components"
  echo
  echo "oplbm bundles the following third-party Go modules (go.mod, all"
  echo "transitive requirements) and the bundled data listed below."
  echo "Regenerated by \`scripts/gen-third-party.sh\`; full license texts for"
  echo "each module ship in \`licenses/\`."
  echo
  echo "| Module | Version | License |"
  echo "|---|---|---|"
  while read -r path version moddir; do
    lic="see module"
    if [ -n "$moddir" ] && [ -d "$moddir" ]; then
      f="$(find "$moddir" -maxdepth 1 \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' \) 2>/dev/null | sort | head -n1 || true)"
      if [ -n "$f" ]; then
        base="$(basename "$f")"
        safe="$(printf '%s' "$path" | tr '/' '_')"
        mkdir -p "$licdir/$safe"
        cp "$f" "$licdir/$safe/$base"
        lic="$base (\`licenses/$safe/\`)"
      fi
    fi
    printf '| %s | %s | %s |\n' "$path" "$version" "$lic"
  done < "$tmp"
  echo
  echo "## Bundled data"
  echo
  echo "- \`internal/library/data/ps2_cd_titles.json\` — project-generated"
  echo "  known-titles list (spec §2.3 #4); ships unpopulated; user-extendable"
  echo "  via \`ps2_cd_titles.user.json\` in the config dir."
  echo "- \`web/dist\` — Svelte SPA compiled from \`web/\` sources in this"
  echo "  repository (build-time devDependencies only, resolved above when"
  echo "  installed; no third-party runtime JS beyond the compiled bundle)."
} > "$md"

rows="$(grep -c '^| ' "$md" || true)"
files="$(find "$licdir" -type f | wc -l)"
echo "wrote $md ($rows table rows) and $licdir/ ($files license files)"
